steps:
- name: 'node:22'
  entrypoint: 'npm'
  args: ['install']

- name: 'node:22'
  entrypoint: 'npm'
  args: ['test']

# Build the image
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=$LOCATION-docker.pkg.dev/$PROJECT_ID/docker/myimage:$COMMIT_SHA"
  - "--file=./Dockerfile-prod"
  - .
  automapSubstitutions: true

# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/docker/myimage:$COMMIT_SHA']

# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'servicename'
    - '--image'
    - '$LOCATION-docker.pkg.dev/$PROJECT_ID/docker/myimage:$COMMIT_SHA'
    - '--region'
    - '$LOCATION'

images:
- "$LOCATION-docker.pkg.dev/$PROJECT_ID/docker/myimage:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
